// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotificationListDTO.proto

package es.encalient;

public final class ProtoNotificationListDTO {
  private ProtoNotificationListDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotificationListDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.encalient.NotificationListDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    java.util.List<es.encalient.ProtoNotificationDTO.NotificationDTO> 
        getItemsList();
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    es.encalient.ProtoNotificationDTO.NotificationDTO getItems(int index);
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    java.util.List<? extends es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>optional int32 PageNumber = 2;</code>
     */
    boolean hasPageNumber();
    /**
     * <code>optional int32 PageNumber = 2;</code>
     */
    int getPageNumber();

    /**
     * <code>optional int32 PageTotal = 3;</code>
     */
    boolean hasPageTotal();
    /**
     * <code>optional int32 PageTotal = 3;</code>
     */
    int getPageTotal();
  }
  /**
   * Protobuf type {@code es.encalient.NotificationListDTO}
   */
  public static final class NotificationListDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:es.encalient.NotificationListDTO)
      NotificationListDTOOrBuilder {
    // Use NotificationListDTO.newBuilder() to construct.
    private NotificationListDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotificationListDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotificationListDTO defaultInstance;
    public static NotificationListDTO getDefaultInstance() {
      return defaultInstance;
    }

    public NotificationListDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotificationListDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<es.encalient.ProtoNotificationDTO.NotificationDTO>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(es.encalient.ProtoNotificationDTO.NotificationDTO.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              pageNumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              pageTotal_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.encalient.ProtoNotificationListDTO.internal_static_es_encalient_NotificationListDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.encalient.ProtoNotificationListDTO.internal_static_es_encalient_NotificationListDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.encalient.ProtoNotificationListDTO.NotificationListDTO.class, es.encalient.ProtoNotificationListDTO.NotificationListDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<NotificationListDTO> PARSER =
        new com.google.protobuf.AbstractParser<NotificationListDTO>() {
      public NotificationListDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotificationListDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NotificationListDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<es.encalient.ProtoNotificationDTO.NotificationDTO> items_;
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    public java.util.List<es.encalient.ProtoNotificationDTO.NotificationDTO> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    public java.util.List<? extends es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    public es.encalient.ProtoNotificationDTO.NotificationDTO getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
     */
    public es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int PAGENUMBER_FIELD_NUMBER = 2;
    private int pageNumber_;
    /**
     * <code>optional int32 PageNumber = 2;</code>
     */
    public boolean hasPageNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 PageNumber = 2;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    public static final int PAGETOTAL_FIELD_NUMBER = 3;
    private int pageTotal_;
    /**
     * <code>optional int32 PageTotal = 3;</code>
     */
    public boolean hasPageTotal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 PageTotal = 3;</code>
     */
    public int getPageTotal() {
      return pageTotal_;
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
      pageNumber_ = 0;
      pageTotal_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, pageNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, pageTotal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageTotal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoNotificationListDTO.NotificationListDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(es.encalient.ProtoNotificationListDTO.NotificationListDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.encalient.NotificationListDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.encalient.NotificationListDTO)
        es.encalient.ProtoNotificationListDTO.NotificationListDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.encalient.ProtoNotificationListDTO.internal_static_es_encalient_NotificationListDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.encalient.ProtoNotificationListDTO.internal_static_es_encalient_NotificationListDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.encalient.ProtoNotificationListDTO.NotificationListDTO.class, es.encalient.ProtoNotificationListDTO.NotificationListDTO.Builder.class);
      }

      // Construct using es.encalient.ProtoNotificationListDTO.NotificationListDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        pageNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageTotal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.encalient.ProtoNotificationListDTO.internal_static_es_encalient_NotificationListDTO_descriptor;
      }

      public es.encalient.ProtoNotificationListDTO.NotificationListDTO getDefaultInstanceForType() {
        return es.encalient.ProtoNotificationListDTO.NotificationListDTO.getDefaultInstance();
      }

      public es.encalient.ProtoNotificationListDTO.NotificationListDTO build() {
        es.encalient.ProtoNotificationListDTO.NotificationListDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.encalient.ProtoNotificationListDTO.NotificationListDTO buildPartial() {
        es.encalient.ProtoNotificationListDTO.NotificationListDTO result = new es.encalient.ProtoNotificationListDTO.NotificationListDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pageNumber_ = pageNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageTotal_ = pageTotal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.encalient.ProtoNotificationListDTO.NotificationListDTO) {
          return mergeFrom((es.encalient.ProtoNotificationListDTO.NotificationListDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.encalient.ProtoNotificationListDTO.NotificationListDTO other) {
        if (other == es.encalient.ProtoNotificationListDTO.NotificationListDTO.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (other.hasPageNumber()) {
          setPageNumber(other.getPageNumber());
        }
        if (other.hasPageTotal()) {
          setPageTotal(other.getPageTotal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.encalient.ProtoNotificationListDTO.NotificationListDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.encalient.ProtoNotificationListDTO.NotificationListDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<es.encalient.ProtoNotificationDTO.NotificationDTO> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<es.encalient.ProtoNotificationDTO.NotificationDTO>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoNotificationDTO.NotificationDTO, es.encalient.ProtoNotificationDTO.NotificationDTO.Builder, es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public java.util.List<es.encalient.ProtoNotificationDTO.NotificationDTO> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public es.encalient.ProtoNotificationDTO.NotificationDTO getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder setItems(
          int index, es.encalient.ProtoNotificationDTO.NotificationDTO value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder setItems(
          int index, es.encalient.ProtoNotificationDTO.NotificationDTO.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder addItems(es.encalient.ProtoNotificationDTO.NotificationDTO value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder addItems(
          int index, es.encalient.ProtoNotificationDTO.NotificationDTO value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder addItems(
          es.encalient.ProtoNotificationDTO.NotificationDTO.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder addItems(
          int index, es.encalient.ProtoNotificationDTO.NotificationDTO.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends es.encalient.ProtoNotificationDTO.NotificationDTO> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public es.encalient.ProtoNotificationDTO.NotificationDTO.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public java.util.List<? extends es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public es.encalient.ProtoNotificationDTO.NotificationDTO.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            es.encalient.ProtoNotificationDTO.NotificationDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public es.encalient.ProtoNotificationDTO.NotificationDTO.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, es.encalient.ProtoNotificationDTO.NotificationDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.NotificationDTO items = 1;</code>
       */
      public java.util.List<es.encalient.ProtoNotificationDTO.NotificationDTO.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoNotificationDTO.NotificationDTO, es.encalient.ProtoNotificationDTO.NotificationDTO.Builder, es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              es.encalient.ProtoNotificationDTO.NotificationDTO, es.encalient.ProtoNotificationDTO.NotificationDTO.Builder, es.encalient.ProtoNotificationDTO.NotificationDTOOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private int pageNumber_ ;
      /**
       * <code>optional int32 PageNumber = 2;</code>
       */
      public boolean hasPageNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 PageNumber = 2;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>optional int32 PageNumber = 2;</code>
       */
      public Builder setPageNumber(int value) {
        bitField0_ |= 0x00000002;
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 PageNumber = 2;</code>
       */
      public Builder clearPageNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      private int pageTotal_ ;
      /**
       * <code>optional int32 PageTotal = 3;</code>
       */
      public boolean hasPageTotal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 PageTotal = 3;</code>
       */
      public int getPageTotal() {
        return pageTotal_;
      }
      /**
       * <code>optional int32 PageTotal = 3;</code>
       */
      public Builder setPageTotal(int value) {
        bitField0_ |= 0x00000004;
        pageTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 PageTotal = 3;</code>
       */
      public Builder clearPageTotal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageTotal_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:es.encalient.NotificationListDTO)
    }

    static {
      defaultInstance = new NotificationListDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:es.encalient.NotificationListDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_encalient_NotificationListDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_es_encalient_NotificationListDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031NotificationListDTO.proto\022\014es.encalien" +
      "t\032\025NotificationDTO.proto\"j\n\023Notification" +
      "ListDTO\022,\n\005items\030\001 \003(\0132\035.es.encalient.No" +
      "tificationDTO\022\022\n\nPageNumber\030\002 \001(\005\022\021\n\tPag" +
      "eTotal\030\003 \001(\005B\032B\030ProtoNotificationListDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          es.encalient.ProtoNotificationDTO.getDescriptor(),
        }, assigner);
    internal_static_es_encalient_NotificationListDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_encalient_NotificationListDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_es_encalient_NotificationListDTO_descriptor,
        new java.lang.String[] { "Items", "PageNumber", "PageTotal", });
    es.encalient.ProtoNotificationDTO.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
