// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SeasonDTO.proto

package es.encalient;

public final class ProtoSeasonDTO {
  private ProtoSeasonDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SeasonDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.encalient.SeasonDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 Id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 Id = 1;</code>
     */
    long getId();

    /**
     * <code>optional int64 League = 2;</code>
     */
    boolean hasLeague();
    /**
     * <code>optional int64 League = 2;</code>
     */
    long getLeague();

    /**
     * <code>optional string Title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string Title = 3;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string Title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    java.util.List<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO> 
        getScoreTableResultList();
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO getScoreTableResult(int index);
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    int getScoreTableResultCount();
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    java.util.List<? extends es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder> 
        getScoreTableResultOrBuilderList();
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder getScoreTableResultOrBuilder(
        int index);

    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    java.util.List<es.encalient.ProtoWeekDTO.WeekDTO> 
        getWeeksList();
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    es.encalient.ProtoWeekDTO.WeekDTO getWeeks(int index);
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    int getWeeksCount();
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    java.util.List<? extends es.encalient.ProtoWeekDTO.WeekDTOOrBuilder> 
        getWeeksOrBuilderList();
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    es.encalient.ProtoWeekDTO.WeekDTOOrBuilder getWeeksOrBuilder(
        int index);

    /**
     * <code>optional string Description = 16;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string Description = 16;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string Description = 16;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string DateFrom = 17;</code>
     */
    boolean hasDateFrom();
    /**
     * <code>optional string DateFrom = 17;</code>
     */
    java.lang.String getDateFrom();
    /**
     * <code>optional string DateFrom = 17;</code>
     */
    com.google.protobuf.ByteString
        getDateFromBytes();

    /**
     * <code>optional string DateTo = 18;</code>
     */
    boolean hasDateTo();
    /**
     * <code>optional string DateTo = 18;</code>
     */
    java.lang.String getDateTo();
    /**
     * <code>optional string DateTo = 18;</code>
     */
    com.google.protobuf.ByteString
        getDateToBytes();
  }
  /**
   * Protobuf type {@code es.encalient.SeasonDTO}
   */
  public static final class SeasonDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:es.encalient.SeasonDTO)
      SeasonDTOOrBuilder {
    // Use SeasonDTO.newBuilder() to construct.
    private SeasonDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SeasonDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SeasonDTO defaultInstance;
    public static SeasonDTO getDefaultInstance() {
      return defaultInstance;
    }

    public SeasonDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SeasonDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              league_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              title_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                scoreTableResult_ = new java.util.ArrayList<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO>();
                mutable_bitField0_ |= 0x00000008;
              }
              scoreTableResult_.add(input.readMessage(es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                weeks_ = new java.util.ArrayList<es.encalient.ProtoWeekDTO.WeekDTO>();
                mutable_bitField0_ |= 0x00000010;
              }
              weeks_.add(input.readMessage(es.encalient.ProtoWeekDTO.WeekDTO.PARSER, extensionRegistry));
              break;
            }
            case 130: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              description_ = bs;
              break;
            }
            case 138: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              dateFrom_ = bs;
              break;
            }
            case 146: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              dateTo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          scoreTableResult_ = java.util.Collections.unmodifiableList(scoreTableResult_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          weeks_ = java.util.Collections.unmodifiableList(weeks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.encalient.ProtoSeasonDTO.internal_static_es_encalient_SeasonDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.encalient.ProtoSeasonDTO.internal_static_es_encalient_SeasonDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.encalient.ProtoSeasonDTO.SeasonDTO.class, es.encalient.ProtoSeasonDTO.SeasonDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<SeasonDTO> PARSER =
        new com.google.protobuf.AbstractParser<SeasonDTO>() {
      public SeasonDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SeasonDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SeasonDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int LEAGUE_FIELD_NUMBER = 2;
    private long league_;
    /**
     * <code>optional int64 League = 2;</code>
     */
    public boolean hasLeague() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 League = 2;</code>
     */
    public long getLeague() {
      return league_;
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    /**
     * <code>optional string Title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string Title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORETABLERESULT_FIELD_NUMBER = 4;
    private java.util.List<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO> scoreTableResult_;
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    public java.util.List<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO> getScoreTableResultList() {
      return scoreTableResult_;
    }
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    public java.util.List<? extends es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder> 
        getScoreTableResultOrBuilderList() {
      return scoreTableResult_;
    }
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    public int getScoreTableResultCount() {
      return scoreTableResult_.size();
    }
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO getScoreTableResult(int index) {
      return scoreTableResult_.get(index);
    }
    /**
     * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
     */
    public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder getScoreTableResultOrBuilder(
        int index) {
      return scoreTableResult_.get(index);
    }

    public static final int WEEKS_FIELD_NUMBER = 5;
    private java.util.List<es.encalient.ProtoWeekDTO.WeekDTO> weeks_;
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    public java.util.List<es.encalient.ProtoWeekDTO.WeekDTO> getWeeksList() {
      return weeks_;
    }
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    public java.util.List<? extends es.encalient.ProtoWeekDTO.WeekDTOOrBuilder> 
        getWeeksOrBuilderList() {
      return weeks_;
    }
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    public int getWeeksCount() {
      return weeks_.size();
    }
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    public es.encalient.ProtoWeekDTO.WeekDTO getWeeks(int index) {
      return weeks_.get(index);
    }
    /**
     * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
     */
    public es.encalient.ProtoWeekDTO.WeekDTOOrBuilder getWeeksOrBuilder(
        int index) {
      return weeks_.get(index);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 16;
    private java.lang.Object description_;
    /**
     * <code>optional string Description = 16;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string Description = 16;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Description = 16;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATEFROM_FIELD_NUMBER = 17;
    private java.lang.Object dateFrom_;
    /**
     * <code>optional string DateFrom = 17;</code>
     */
    public boolean hasDateFrom() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string DateFrom = 17;</code>
     */
    public java.lang.String getDateFrom() {
      java.lang.Object ref = dateFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dateFrom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string DateFrom = 17;</code>
     */
    public com.google.protobuf.ByteString
        getDateFromBytes() {
      java.lang.Object ref = dateFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATETO_FIELD_NUMBER = 18;
    private java.lang.Object dateTo_;
    /**
     * <code>optional string DateTo = 18;</code>
     */
    public boolean hasDateTo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string DateTo = 18;</code>
     */
    public java.lang.String getDateTo() {
      java.lang.Object ref = dateTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dateTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string DateTo = 18;</code>
     */
    public com.google.protobuf.ByteString
        getDateToBytes() {
      java.lang.Object ref = dateTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      league_ = 0L;
      title_ = "";
      scoreTableResult_ = java.util.Collections.emptyList();
      weeks_ = java.util.Collections.emptyList();
      description_ = "";
      dateFrom_ = "";
      dateTo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, league_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTitleBytes());
      }
      for (int i = 0; i < scoreTableResult_.size(); i++) {
        output.writeMessage(4, scoreTableResult_.get(i));
      }
      for (int i = 0; i < weeks_.size(); i++) {
        output.writeMessage(5, weeks_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(16, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(17, getDateFromBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(18, getDateToBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, league_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      for (int i = 0; i < scoreTableResult_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, scoreTableResult_.get(i));
      }
      for (int i = 0; i < weeks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, weeks_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getDateFromBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getDateToBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoSeasonDTO.SeasonDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(es.encalient.ProtoSeasonDTO.SeasonDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.encalient.SeasonDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.encalient.SeasonDTO)
        es.encalient.ProtoSeasonDTO.SeasonDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.encalient.ProtoSeasonDTO.internal_static_es_encalient_SeasonDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.encalient.ProtoSeasonDTO.internal_static_es_encalient_SeasonDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.encalient.ProtoSeasonDTO.SeasonDTO.class, es.encalient.ProtoSeasonDTO.SeasonDTO.Builder.class);
      }

      // Construct using es.encalient.ProtoSeasonDTO.SeasonDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getScoreTableResultFieldBuilder();
          getWeeksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        league_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (scoreTableResultBuilder_ == null) {
          scoreTableResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          scoreTableResultBuilder_.clear();
        }
        if (weeksBuilder_ == null) {
          weeks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          weeksBuilder_.clear();
        }
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        dateFrom_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        dateTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.encalient.ProtoSeasonDTO.internal_static_es_encalient_SeasonDTO_descriptor;
      }

      public es.encalient.ProtoSeasonDTO.SeasonDTO getDefaultInstanceForType() {
        return es.encalient.ProtoSeasonDTO.SeasonDTO.getDefaultInstance();
      }

      public es.encalient.ProtoSeasonDTO.SeasonDTO build() {
        es.encalient.ProtoSeasonDTO.SeasonDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.encalient.ProtoSeasonDTO.SeasonDTO buildPartial() {
        es.encalient.ProtoSeasonDTO.SeasonDTO result = new es.encalient.ProtoSeasonDTO.SeasonDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.league_ = league_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (scoreTableResultBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            scoreTableResult_ = java.util.Collections.unmodifiableList(scoreTableResult_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.scoreTableResult_ = scoreTableResult_;
        } else {
          result.scoreTableResult_ = scoreTableResultBuilder_.build();
        }
        if (weeksBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            weeks_ = java.util.Collections.unmodifiableList(weeks_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.weeks_ = weeks_;
        } else {
          result.weeks_ = weeksBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dateFrom_ = dateFrom_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.dateTo_ = dateTo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.encalient.ProtoSeasonDTO.SeasonDTO) {
          return mergeFrom((es.encalient.ProtoSeasonDTO.SeasonDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.encalient.ProtoSeasonDTO.SeasonDTO other) {
        if (other == es.encalient.ProtoSeasonDTO.SeasonDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLeague()) {
          setLeague(other.getLeague());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000004;
          title_ = other.title_;
          onChanged();
        }
        if (scoreTableResultBuilder_ == null) {
          if (!other.scoreTableResult_.isEmpty()) {
            if (scoreTableResult_.isEmpty()) {
              scoreTableResult_ = other.scoreTableResult_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureScoreTableResultIsMutable();
              scoreTableResult_.addAll(other.scoreTableResult_);
            }
            onChanged();
          }
        } else {
          if (!other.scoreTableResult_.isEmpty()) {
            if (scoreTableResultBuilder_.isEmpty()) {
              scoreTableResultBuilder_.dispose();
              scoreTableResultBuilder_ = null;
              scoreTableResult_ = other.scoreTableResult_;
              bitField0_ = (bitField0_ & ~0x00000008);
              scoreTableResultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getScoreTableResultFieldBuilder() : null;
            } else {
              scoreTableResultBuilder_.addAllMessages(other.scoreTableResult_);
            }
          }
        }
        if (weeksBuilder_ == null) {
          if (!other.weeks_.isEmpty()) {
            if (weeks_.isEmpty()) {
              weeks_ = other.weeks_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureWeeksIsMutable();
              weeks_.addAll(other.weeks_);
            }
            onChanged();
          }
        } else {
          if (!other.weeks_.isEmpty()) {
            if (weeksBuilder_.isEmpty()) {
              weeksBuilder_.dispose();
              weeksBuilder_ = null;
              weeks_ = other.weeks_;
              bitField0_ = (bitField0_ & ~0x00000010);
              weeksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWeeksFieldBuilder() : null;
            } else {
              weeksBuilder_.addAllMessages(other.weeks_);
            }
          }
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000020;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasDateFrom()) {
          bitField0_ |= 0x00000040;
          dateFrom_ = other.dateFrom_;
          onChanged();
        }
        if (other.hasDateTo()) {
          bitField0_ |= 0x00000080;
          dateTo_ = other.dateTo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.encalient.ProtoSeasonDTO.SeasonDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.encalient.ProtoSeasonDTO.SeasonDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long league_ ;
      /**
       * <code>optional int64 League = 2;</code>
       */
      public boolean hasLeague() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 League = 2;</code>
       */
      public long getLeague() {
        return league_;
      }
      /**
       * <code>optional int64 League = 2;</code>
       */
      public Builder setLeague(long value) {
        bitField0_ |= 0x00000002;
        league_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 League = 2;</code>
       */
      public Builder clearLeague() {
        bitField0_ = (bitField0_ & ~0x00000002);
        league_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string Title = 3;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }

      private java.util.List<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO> scoreTableResult_ =
        java.util.Collections.emptyList();
      private void ensureScoreTableResultIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          scoreTableResult_ = new java.util.ArrayList<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO>(scoreTableResult_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder> scoreTableResultBuilder_;

      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public java.util.List<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO> getScoreTableResultList() {
        if (scoreTableResultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(scoreTableResult_);
        } else {
          return scoreTableResultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public int getScoreTableResultCount() {
        if (scoreTableResultBuilder_ == null) {
          return scoreTableResult_.size();
        } else {
          return scoreTableResultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO getScoreTableResult(int index) {
        if (scoreTableResultBuilder_ == null) {
          return scoreTableResult_.get(index);
        } else {
          return scoreTableResultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder setScoreTableResult(
          int index, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO value) {
        if (scoreTableResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoreTableResultIsMutable();
          scoreTableResult_.set(index, value);
          onChanged();
        } else {
          scoreTableResultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder setScoreTableResult(
          int index, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder builderForValue) {
        if (scoreTableResultBuilder_ == null) {
          ensureScoreTableResultIsMutable();
          scoreTableResult_.set(index, builderForValue.build());
          onChanged();
        } else {
          scoreTableResultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder addScoreTableResult(es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO value) {
        if (scoreTableResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoreTableResultIsMutable();
          scoreTableResult_.add(value);
          onChanged();
        } else {
          scoreTableResultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder addScoreTableResult(
          int index, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO value) {
        if (scoreTableResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoreTableResultIsMutable();
          scoreTableResult_.add(index, value);
          onChanged();
        } else {
          scoreTableResultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder addScoreTableResult(
          es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder builderForValue) {
        if (scoreTableResultBuilder_ == null) {
          ensureScoreTableResultIsMutable();
          scoreTableResult_.add(builderForValue.build());
          onChanged();
        } else {
          scoreTableResultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder addScoreTableResult(
          int index, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder builderForValue) {
        if (scoreTableResultBuilder_ == null) {
          ensureScoreTableResultIsMutable();
          scoreTableResult_.add(index, builderForValue.build());
          onChanged();
        } else {
          scoreTableResultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder addAllScoreTableResult(
          java.lang.Iterable<? extends es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO> values) {
        if (scoreTableResultBuilder_ == null) {
          ensureScoreTableResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, scoreTableResult_);
          onChanged();
        } else {
          scoreTableResultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder clearScoreTableResult() {
        if (scoreTableResultBuilder_ == null) {
          scoreTableResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          scoreTableResultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public Builder removeScoreTableResult(int index) {
        if (scoreTableResultBuilder_ == null) {
          ensureScoreTableResultIsMutable();
          scoreTableResult_.remove(index);
          onChanged();
        } else {
          scoreTableResultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder getScoreTableResultBuilder(
          int index) {
        return getScoreTableResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder getScoreTableResultOrBuilder(
          int index) {
        if (scoreTableResultBuilder_ == null) {
          return scoreTableResult_.get(index);  } else {
          return scoreTableResultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public java.util.List<? extends es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder> 
           getScoreTableResultOrBuilderList() {
        if (scoreTableResultBuilder_ != null) {
          return scoreTableResultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(scoreTableResult_);
        }
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder addScoreTableResultBuilder() {
        return getScoreTableResultFieldBuilder().addBuilder(
            es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder addScoreTableResultBuilder(
          int index) {
        return getScoreTableResultFieldBuilder().addBuilder(
            index, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.ScoreTableResultDTO ScoreTableResult = 4;</code>
       */
      public java.util.List<es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder> 
           getScoreTableResultBuilderList() {
        return getScoreTableResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder> 
          getScoreTableResultFieldBuilder() {
        if (scoreTableResultBuilder_ == null) {
          scoreTableResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder>(
                  scoreTableResult_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          scoreTableResult_ = null;
        }
        return scoreTableResultBuilder_;
      }

      private java.util.List<es.encalient.ProtoWeekDTO.WeekDTO> weeks_ =
        java.util.Collections.emptyList();
      private void ensureWeeksIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          weeks_ = new java.util.ArrayList<es.encalient.ProtoWeekDTO.WeekDTO>(weeks_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoWeekDTO.WeekDTO, es.encalient.ProtoWeekDTO.WeekDTO.Builder, es.encalient.ProtoWeekDTO.WeekDTOOrBuilder> weeksBuilder_;

      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public java.util.List<es.encalient.ProtoWeekDTO.WeekDTO> getWeeksList() {
        if (weeksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(weeks_);
        } else {
          return weeksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public int getWeeksCount() {
        if (weeksBuilder_ == null) {
          return weeks_.size();
        } else {
          return weeksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public es.encalient.ProtoWeekDTO.WeekDTO getWeeks(int index) {
        if (weeksBuilder_ == null) {
          return weeks_.get(index);
        } else {
          return weeksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder setWeeks(
          int index, es.encalient.ProtoWeekDTO.WeekDTO value) {
        if (weeksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWeeksIsMutable();
          weeks_.set(index, value);
          onChanged();
        } else {
          weeksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder setWeeks(
          int index, es.encalient.ProtoWeekDTO.WeekDTO.Builder builderForValue) {
        if (weeksBuilder_ == null) {
          ensureWeeksIsMutable();
          weeks_.set(index, builderForValue.build());
          onChanged();
        } else {
          weeksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder addWeeks(es.encalient.ProtoWeekDTO.WeekDTO value) {
        if (weeksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWeeksIsMutable();
          weeks_.add(value);
          onChanged();
        } else {
          weeksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder addWeeks(
          int index, es.encalient.ProtoWeekDTO.WeekDTO value) {
        if (weeksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWeeksIsMutable();
          weeks_.add(index, value);
          onChanged();
        } else {
          weeksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder addWeeks(
          es.encalient.ProtoWeekDTO.WeekDTO.Builder builderForValue) {
        if (weeksBuilder_ == null) {
          ensureWeeksIsMutable();
          weeks_.add(builderForValue.build());
          onChanged();
        } else {
          weeksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder addWeeks(
          int index, es.encalient.ProtoWeekDTO.WeekDTO.Builder builderForValue) {
        if (weeksBuilder_ == null) {
          ensureWeeksIsMutable();
          weeks_.add(index, builderForValue.build());
          onChanged();
        } else {
          weeksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder addAllWeeks(
          java.lang.Iterable<? extends es.encalient.ProtoWeekDTO.WeekDTO> values) {
        if (weeksBuilder_ == null) {
          ensureWeeksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, weeks_);
          onChanged();
        } else {
          weeksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder clearWeeks() {
        if (weeksBuilder_ == null) {
          weeks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          weeksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public Builder removeWeeks(int index) {
        if (weeksBuilder_ == null) {
          ensureWeeksIsMutable();
          weeks_.remove(index);
          onChanged();
        } else {
          weeksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public es.encalient.ProtoWeekDTO.WeekDTO.Builder getWeeksBuilder(
          int index) {
        return getWeeksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public es.encalient.ProtoWeekDTO.WeekDTOOrBuilder getWeeksOrBuilder(
          int index) {
        if (weeksBuilder_ == null) {
          return weeks_.get(index);  } else {
          return weeksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public java.util.List<? extends es.encalient.ProtoWeekDTO.WeekDTOOrBuilder> 
           getWeeksOrBuilderList() {
        if (weeksBuilder_ != null) {
          return weeksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(weeks_);
        }
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public es.encalient.ProtoWeekDTO.WeekDTO.Builder addWeeksBuilder() {
        return getWeeksFieldBuilder().addBuilder(
            es.encalient.ProtoWeekDTO.WeekDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public es.encalient.ProtoWeekDTO.WeekDTO.Builder addWeeksBuilder(
          int index) {
        return getWeeksFieldBuilder().addBuilder(
            index, es.encalient.ProtoWeekDTO.WeekDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.WeekDTO Weeks = 5;</code>
       */
      public java.util.List<es.encalient.ProtoWeekDTO.WeekDTO.Builder> 
           getWeeksBuilderList() {
        return getWeeksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoWeekDTO.WeekDTO, es.encalient.ProtoWeekDTO.WeekDTO.Builder, es.encalient.ProtoWeekDTO.WeekDTOOrBuilder> 
          getWeeksFieldBuilder() {
        if (weeksBuilder_ == null) {
          weeksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              es.encalient.ProtoWeekDTO.WeekDTO, es.encalient.ProtoWeekDTO.WeekDTO.Builder, es.encalient.ProtoWeekDTO.WeekDTOOrBuilder>(
                  weeks_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          weeks_ = null;
        }
        return weeksBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string Description = 16;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000020);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateFrom_ = "";
      /**
       * <code>optional string DateFrom = 17;</code>
       */
      public boolean hasDateFrom() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string DateFrom = 17;</code>
       */
      public java.lang.String getDateFrom() {
        java.lang.Object ref = dateFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dateFrom_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string DateFrom = 17;</code>
       */
      public com.google.protobuf.ByteString
          getDateFromBytes() {
        java.lang.Object ref = dateFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string DateFrom = 17;</code>
       */
      public Builder setDateFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        dateFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateFrom = 17;</code>
       */
      public Builder clearDateFrom() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dateFrom_ = getDefaultInstance().getDateFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateFrom = 17;</code>
       */
      public Builder setDateFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        dateFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateTo_ = "";
      /**
       * <code>optional string DateTo = 18;</code>
       */
      public boolean hasDateTo() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string DateTo = 18;</code>
       */
      public java.lang.String getDateTo() {
        java.lang.Object ref = dateTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dateTo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string DateTo = 18;</code>
       */
      public com.google.protobuf.ByteString
          getDateToBytes() {
        java.lang.Object ref = dateTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string DateTo = 18;</code>
       */
      public Builder setDateTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        dateTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateTo = 18;</code>
       */
      public Builder clearDateTo() {
        bitField0_ = (bitField0_ & ~0x00000080);
        dateTo_ = getDefaultInstance().getDateTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateTo = 18;</code>
       */
      public Builder setDateToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        dateTo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:es.encalient.SeasonDTO)
    }

    static {
      defaultInstance = new SeasonDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:es.encalient.SeasonDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_encalient_SeasonDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_es_encalient_SeasonDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SeasonDTO.proto\022\014es.encalient\032\031ScoreTa" +
      "bleResultDTO.proto\032\rWeekDTO.proto\"\320\001\n\tSe" +
      "asonDTO\022\n\n\002Id\030\001 \001(\003\022\016\n\006League\030\002 \001(\003\022\r\n\005T" +
      "itle\030\003 \001(\t\022;\n\020ScoreTableResult\030\004 \003(\0132!.e" +
      "s.encalient.ScoreTableResultDTO\022$\n\005Weeks" +
      "\030\005 \003(\0132\025.es.encalient.WeekDTO\022\023\n\013Descrip" +
      "tion\030\020 \001(\t\022\020\n\010DateFrom\030\021 \001(\t\022\016\n\006DateTo\030\022" +
      " \001(\tB\020B\016ProtoSeasonDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          es.encalient.ProtoScoreTableResultDTO.getDescriptor(),
          es.encalient.ProtoWeekDTO.getDescriptor(),
        }, assigner);
    internal_static_es_encalient_SeasonDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_encalient_SeasonDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_es_encalient_SeasonDTO_descriptor,
        new java.lang.String[] { "Id", "League", "Title", "ScoreTableResult", "Weeks", "Description", "DateFrom", "DateTo", });
    es.encalient.ProtoScoreTableResultDTO.getDescriptor();
    es.encalient.ProtoWeekDTO.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
