// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScoreTableResultDTO.proto

package es.encalient;

public final class ProtoScoreTableResultDTO {
  private ProtoScoreTableResultDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ScoreTableResultDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.encalient.ScoreTableResultDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .es.encalient.TeamDTO Team = 1;</code>
     */
    boolean hasTeam();
    /**
     * <code>optional .es.encalient.TeamDTO Team = 1;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTO getTeam();
    /**
     * <code>optional .es.encalient.TeamDTO Team = 1;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeamOrBuilder();

    /**
     * <code>optional int64 GamesPlayed = 2;</code>
     */
    boolean hasGamesPlayed();
    /**
     * <code>optional int64 GamesPlayed = 2;</code>
     */
    long getGamesPlayed();

    /**
     * <code>optional int64 GamesWined = 3;</code>
     */
    boolean hasGamesWined();
    /**
     * <code>optional int64 GamesWined = 3;</code>
     */
    long getGamesWined();

    /**
     * <code>optional int64 GamesDrawn = 4;</code>
     */
    boolean hasGamesDrawn();
    /**
     * <code>optional int64 GamesDrawn = 4;</code>
     */
    long getGamesDrawn();

    /**
     * <code>optional int64 GamesLost = 5;</code>
     */
    boolean hasGamesLost();
    /**
     * <code>optional int64 GamesLost = 5;</code>
     */
    long getGamesLost();

    /**
     * <code>optional int64 ScoreFavor = 6;</code>
     */
    boolean hasScoreFavor();
    /**
     * <code>optional int64 ScoreFavor = 6;</code>
     */
    long getScoreFavor();

    /**
     * <code>optional int64 ScoreAgainst = 7;</code>
     */
    boolean hasScoreAgainst();
    /**
     * <code>optional int64 ScoreAgainst = 7;</code>
     */
    long getScoreAgainst();

    /**
     * <code>optional int64 ScoreDifference = 8;</code>
     */
    boolean hasScoreDifference();
    /**
     * <code>optional int64 ScoreDifference = 8;</code>
     */
    long getScoreDifference();

    /**
     * <code>optional int64 Points = 9;</code>
     */
    boolean hasPoints();
    /**
     * <code>optional int64 Points = 9;</code>
     */
    long getPoints();

    /**
     * <code>optional int64 Position = 10;</code>
     */
    boolean hasPosition();
    /**
     * <code>optional int64 Position = 10;</code>
     */
    long getPosition();

    /**
     * <code>optional string League = 11;</code>
     */
    boolean hasLeague();
    /**
     * <code>optional string League = 11;</code>
     */
    java.lang.String getLeague();
    /**
     * <code>optional string League = 11;</code>
     */
    com.google.protobuf.ByteString
        getLeagueBytes();
  }
  /**
   * Protobuf type {@code es.encalient.ScoreTableResultDTO}
   */
  public static final class ScoreTableResultDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:es.encalient.ScoreTableResultDTO)
      ScoreTableResultDTOOrBuilder {
    // Use ScoreTableResultDTO.newBuilder() to construct.
    private ScoreTableResultDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ScoreTableResultDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ScoreTableResultDTO defaultInstance;
    public static ScoreTableResultDTO getDefaultInstance() {
      return defaultInstance;
    }

    public ScoreTableResultDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ScoreTableResultDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              es.encalient.ProtoTeamDTO.TeamDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = team_.toBuilder();
              }
              team_ = input.readMessage(es.encalient.ProtoTeamDTO.TeamDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(team_);
                team_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gamesPlayed_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gamesWined_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gamesDrawn_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              gamesLost_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              scoreFavor_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              scoreAgainst_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              scoreDifference_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              points_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              position_ = input.readInt64();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              league_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.encalient.ProtoScoreTableResultDTO.internal_static_es_encalient_ScoreTableResultDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.encalient.ProtoScoreTableResultDTO.internal_static_es_encalient_ScoreTableResultDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.class, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<ScoreTableResultDTO> PARSER =
        new com.google.protobuf.AbstractParser<ScoreTableResultDTO>() {
      public ScoreTableResultDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScoreTableResultDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreTableResultDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEAM_FIELD_NUMBER = 1;
    private es.encalient.ProtoTeamDTO.TeamDTO team_;
    /**
     * <code>optional .es.encalient.TeamDTO Team = 1;</code>
     */
    public boolean hasTeam() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .es.encalient.TeamDTO Team = 1;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTO getTeam() {
      return team_;
    }
    /**
     * <code>optional .es.encalient.TeamDTO Team = 1;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeamOrBuilder() {
      return team_;
    }

    public static final int GAMESPLAYED_FIELD_NUMBER = 2;
    private long gamesPlayed_;
    /**
     * <code>optional int64 GamesPlayed = 2;</code>
     */
    public boolean hasGamesPlayed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 GamesPlayed = 2;</code>
     */
    public long getGamesPlayed() {
      return gamesPlayed_;
    }

    public static final int GAMESWINED_FIELD_NUMBER = 3;
    private long gamesWined_;
    /**
     * <code>optional int64 GamesWined = 3;</code>
     */
    public boolean hasGamesWined() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 GamesWined = 3;</code>
     */
    public long getGamesWined() {
      return gamesWined_;
    }

    public static final int GAMESDRAWN_FIELD_NUMBER = 4;
    private long gamesDrawn_;
    /**
     * <code>optional int64 GamesDrawn = 4;</code>
     */
    public boolean hasGamesDrawn() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 GamesDrawn = 4;</code>
     */
    public long getGamesDrawn() {
      return gamesDrawn_;
    }

    public static final int GAMESLOST_FIELD_NUMBER = 5;
    private long gamesLost_;
    /**
     * <code>optional int64 GamesLost = 5;</code>
     */
    public boolean hasGamesLost() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 GamesLost = 5;</code>
     */
    public long getGamesLost() {
      return gamesLost_;
    }

    public static final int SCOREFAVOR_FIELD_NUMBER = 6;
    private long scoreFavor_;
    /**
     * <code>optional int64 ScoreFavor = 6;</code>
     */
    public boolean hasScoreFavor() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 ScoreFavor = 6;</code>
     */
    public long getScoreFavor() {
      return scoreFavor_;
    }

    public static final int SCOREAGAINST_FIELD_NUMBER = 7;
    private long scoreAgainst_;
    /**
     * <code>optional int64 ScoreAgainst = 7;</code>
     */
    public boolean hasScoreAgainst() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 ScoreAgainst = 7;</code>
     */
    public long getScoreAgainst() {
      return scoreAgainst_;
    }

    public static final int SCOREDIFFERENCE_FIELD_NUMBER = 8;
    private long scoreDifference_;
    /**
     * <code>optional int64 ScoreDifference = 8;</code>
     */
    public boolean hasScoreDifference() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 ScoreDifference = 8;</code>
     */
    public long getScoreDifference() {
      return scoreDifference_;
    }

    public static final int POINTS_FIELD_NUMBER = 9;
    private long points_;
    /**
     * <code>optional int64 Points = 9;</code>
     */
    public boolean hasPoints() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 Points = 9;</code>
     */
    public long getPoints() {
      return points_;
    }

    public static final int POSITION_FIELD_NUMBER = 10;
    private long position_;
    /**
     * <code>optional int64 Position = 10;</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 Position = 10;</code>
     */
    public long getPosition() {
      return position_;
    }

    public static final int LEAGUE_FIELD_NUMBER = 11;
    private java.lang.Object league_;
    /**
     * <code>optional string League = 11;</code>
     */
    public boolean hasLeague() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string League = 11;</code>
     */
    public java.lang.String getLeague() {
      java.lang.Object ref = league_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          league_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string League = 11;</code>
     */
    public com.google.protobuf.ByteString
        getLeagueBytes() {
      java.lang.Object ref = league_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        league_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      team_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
      gamesPlayed_ = 0L;
      gamesWined_ = 0L;
      gamesDrawn_ = 0L;
      gamesLost_ = 0L;
      scoreFavor_ = 0L;
      scoreAgainst_ = 0L;
      scoreDifference_ = 0L;
      points_ = 0L;
      position_ = 0L;
      league_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, team_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, gamesPlayed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, gamesWined_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, gamesDrawn_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, gamesLost_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, scoreFavor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, scoreAgainst_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, scoreDifference_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, points_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, position_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getLeagueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, team_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, gamesPlayed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, gamesWined_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, gamesDrawn_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, gamesLost_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, scoreFavor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, scoreAgainst_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, scoreDifference_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, points_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, position_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getLeagueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.encalient.ScoreTableResultDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.encalient.ScoreTableResultDTO)
        es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.encalient.ProtoScoreTableResultDTO.internal_static_es_encalient_ScoreTableResultDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.encalient.ProtoScoreTableResultDTO.internal_static_es_encalient_ScoreTableResultDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.class, es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.Builder.class);
      }

      // Construct using es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTeamFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (teamBuilder_ == null) {
          team_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        gamesPlayed_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        gamesWined_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        gamesDrawn_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        gamesLost_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        scoreFavor_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        scoreAgainst_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        scoreDifference_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        points_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        position_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        league_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.encalient.ProtoScoreTableResultDTO.internal_static_es_encalient_ScoreTableResultDTO_descriptor;
      }

      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO getDefaultInstanceForType() {
        return es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.getDefaultInstance();
      }

      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO build() {
        es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO buildPartial() {
        es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO result = new es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (teamBuilder_ == null) {
          result.team_ = team_;
        } else {
          result.team_ = teamBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gamesPlayed_ = gamesPlayed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gamesWined_ = gamesWined_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gamesDrawn_ = gamesDrawn_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gamesLost_ = gamesLost_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.scoreFavor_ = scoreFavor_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.scoreAgainst_ = scoreAgainst_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.scoreDifference_ = scoreDifference_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.points_ = points_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.position_ = position_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.league_ = league_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO) {
          return mergeFrom((es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO other) {
        if (other == es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO.getDefaultInstance()) return this;
        if (other.hasTeam()) {
          mergeTeam(other.getTeam());
        }
        if (other.hasGamesPlayed()) {
          setGamesPlayed(other.getGamesPlayed());
        }
        if (other.hasGamesWined()) {
          setGamesWined(other.getGamesWined());
        }
        if (other.hasGamesDrawn()) {
          setGamesDrawn(other.getGamesDrawn());
        }
        if (other.hasGamesLost()) {
          setGamesLost(other.getGamesLost());
        }
        if (other.hasScoreFavor()) {
          setScoreFavor(other.getScoreFavor());
        }
        if (other.hasScoreAgainst()) {
          setScoreAgainst(other.getScoreAgainst());
        }
        if (other.hasScoreDifference()) {
          setScoreDifference(other.getScoreDifference());
        }
        if (other.hasPoints()) {
          setPoints(other.getPoints());
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        if (other.hasLeague()) {
          bitField0_ |= 0x00000400;
          league_ = other.league_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.encalient.ProtoScoreTableResultDTO.ScoreTableResultDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private es.encalient.ProtoTeamDTO.TeamDTO team_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> teamBuilder_;
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public boolean hasTeam() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO getTeam() {
        if (teamBuilder_ == null) {
          return team_;
        } else {
          return teamBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public Builder setTeam(es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (teamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          team_ = value;
          onChanged();
        } else {
          teamBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public Builder setTeam(
          es.encalient.ProtoTeamDTO.TeamDTO.Builder builderForValue) {
        if (teamBuilder_ == null) {
          team_ = builderForValue.build();
          onChanged();
        } else {
          teamBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public Builder mergeTeam(es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (teamBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              team_ != es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance()) {
            team_ =
              es.encalient.ProtoTeamDTO.TeamDTO.newBuilder(team_).mergeFrom(value).buildPartial();
          } else {
            team_ = value;
          }
          onChanged();
        } else {
          teamBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public Builder clearTeam() {
        if (teamBuilder_ == null) {
          team_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
          onChanged();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO.Builder getTeamBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTeamFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeamOrBuilder() {
        if (teamBuilder_ != null) {
          return teamBuilder_.getMessageOrBuilder();
        } else {
          return team_;
        }
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> 
          getTeamFieldBuilder() {
        if (teamBuilder_ == null) {
          teamBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder>(
                  getTeam(),
                  getParentForChildren(),
                  isClean());
          team_ = null;
        }
        return teamBuilder_;
      }

      private long gamesPlayed_ ;
      /**
       * <code>optional int64 GamesPlayed = 2;</code>
       */
      public boolean hasGamesPlayed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 GamesPlayed = 2;</code>
       */
      public long getGamesPlayed() {
        return gamesPlayed_;
      }
      /**
       * <code>optional int64 GamesPlayed = 2;</code>
       */
      public Builder setGamesPlayed(long value) {
        bitField0_ |= 0x00000002;
        gamesPlayed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 GamesPlayed = 2;</code>
       */
      public Builder clearGamesPlayed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gamesPlayed_ = 0L;
        onChanged();
        return this;
      }

      private long gamesWined_ ;
      /**
       * <code>optional int64 GamesWined = 3;</code>
       */
      public boolean hasGamesWined() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 GamesWined = 3;</code>
       */
      public long getGamesWined() {
        return gamesWined_;
      }
      /**
       * <code>optional int64 GamesWined = 3;</code>
       */
      public Builder setGamesWined(long value) {
        bitField0_ |= 0x00000004;
        gamesWined_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 GamesWined = 3;</code>
       */
      public Builder clearGamesWined() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gamesWined_ = 0L;
        onChanged();
        return this;
      }

      private long gamesDrawn_ ;
      /**
       * <code>optional int64 GamesDrawn = 4;</code>
       */
      public boolean hasGamesDrawn() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 GamesDrawn = 4;</code>
       */
      public long getGamesDrawn() {
        return gamesDrawn_;
      }
      /**
       * <code>optional int64 GamesDrawn = 4;</code>
       */
      public Builder setGamesDrawn(long value) {
        bitField0_ |= 0x00000008;
        gamesDrawn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 GamesDrawn = 4;</code>
       */
      public Builder clearGamesDrawn() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gamesDrawn_ = 0L;
        onChanged();
        return this;
      }

      private long gamesLost_ ;
      /**
       * <code>optional int64 GamesLost = 5;</code>
       */
      public boolean hasGamesLost() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 GamesLost = 5;</code>
       */
      public long getGamesLost() {
        return gamesLost_;
      }
      /**
       * <code>optional int64 GamesLost = 5;</code>
       */
      public Builder setGamesLost(long value) {
        bitField0_ |= 0x00000010;
        gamesLost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 GamesLost = 5;</code>
       */
      public Builder clearGamesLost() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gamesLost_ = 0L;
        onChanged();
        return this;
      }

      private long scoreFavor_ ;
      /**
       * <code>optional int64 ScoreFavor = 6;</code>
       */
      public boolean hasScoreFavor() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 ScoreFavor = 6;</code>
       */
      public long getScoreFavor() {
        return scoreFavor_;
      }
      /**
       * <code>optional int64 ScoreFavor = 6;</code>
       */
      public Builder setScoreFavor(long value) {
        bitField0_ |= 0x00000020;
        scoreFavor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ScoreFavor = 6;</code>
       */
      public Builder clearScoreFavor() {
        bitField0_ = (bitField0_ & ~0x00000020);
        scoreFavor_ = 0L;
        onChanged();
        return this;
      }

      private long scoreAgainst_ ;
      /**
       * <code>optional int64 ScoreAgainst = 7;</code>
       */
      public boolean hasScoreAgainst() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 ScoreAgainst = 7;</code>
       */
      public long getScoreAgainst() {
        return scoreAgainst_;
      }
      /**
       * <code>optional int64 ScoreAgainst = 7;</code>
       */
      public Builder setScoreAgainst(long value) {
        bitField0_ |= 0x00000040;
        scoreAgainst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ScoreAgainst = 7;</code>
       */
      public Builder clearScoreAgainst() {
        bitField0_ = (bitField0_ & ~0x00000040);
        scoreAgainst_ = 0L;
        onChanged();
        return this;
      }

      private long scoreDifference_ ;
      /**
       * <code>optional int64 ScoreDifference = 8;</code>
       */
      public boolean hasScoreDifference() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 ScoreDifference = 8;</code>
       */
      public long getScoreDifference() {
        return scoreDifference_;
      }
      /**
       * <code>optional int64 ScoreDifference = 8;</code>
       */
      public Builder setScoreDifference(long value) {
        bitField0_ |= 0x00000080;
        scoreDifference_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ScoreDifference = 8;</code>
       */
      public Builder clearScoreDifference() {
        bitField0_ = (bitField0_ & ~0x00000080);
        scoreDifference_ = 0L;
        onChanged();
        return this;
      }

      private long points_ ;
      /**
       * <code>optional int64 Points = 9;</code>
       */
      public boolean hasPoints() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 Points = 9;</code>
       */
      public long getPoints() {
        return points_;
      }
      /**
       * <code>optional int64 Points = 9;</code>
       */
      public Builder setPoints(long value) {
        bitField0_ |= 0x00000100;
        points_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Points = 9;</code>
       */
      public Builder clearPoints() {
        bitField0_ = (bitField0_ & ~0x00000100);
        points_ = 0L;
        onChanged();
        return this;
      }

      private long position_ ;
      /**
       * <code>optional int64 Position = 10;</code>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 Position = 10;</code>
       */
      public long getPosition() {
        return position_;
      }
      /**
       * <code>optional int64 Position = 10;</code>
       */
      public Builder setPosition(long value) {
        bitField0_ |= 0x00000200;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Position = 10;</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000200);
        position_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object league_ = "";
      /**
       * <code>optional string League = 11;</code>
       */
      public boolean hasLeague() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string League = 11;</code>
       */
      public java.lang.String getLeague() {
        java.lang.Object ref = league_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            league_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string League = 11;</code>
       */
      public com.google.protobuf.ByteString
          getLeagueBytes() {
        java.lang.Object ref = league_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          league_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string League = 11;</code>
       */
      public Builder setLeague(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        league_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string League = 11;</code>
       */
      public Builder clearLeague() {
        bitField0_ = (bitField0_ & ~0x00000400);
        league_ = getDefaultInstance().getLeague();
        onChanged();
        return this;
      }
      /**
       * <code>optional string League = 11;</code>
       */
      public Builder setLeagueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        league_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:es.encalient.ScoreTableResultDTO)
    }

    static {
      defaultInstance = new ScoreTableResultDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:es.encalient.ScoreTableResultDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_encalient_ScoreTableResultDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_es_encalient_ScoreTableResultDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ScoreTableResultDTO.proto\022\014es.encalien" +
      "t\032\rTeamDTO.proto\"\377\001\n\023ScoreTableResultDTO" +
      "\022#\n\004Team\030\001 \001(\0132\025.es.encalient.TeamDTO\022\023\n" +
      "\013GamesPlayed\030\002 \001(\003\022\022\n\nGamesWined\030\003 \001(\003\022\022" +
      "\n\nGamesDrawn\030\004 \001(\003\022\021\n\tGamesLost\030\005 \001(\003\022\022\n" +
      "\nScoreFavor\030\006 \001(\003\022\024\n\014ScoreAgainst\030\007 \001(\003\022" +
      "\027\n\017ScoreDifference\030\010 \001(\003\022\016\n\006Points\030\t \001(\003" +
      "\022\020\n\010Position\030\n \001(\003\022\016\n\006League\030\013 \001(\tB\032B\030Pr" +
      "otoScoreTableResultDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          es.encalient.ProtoTeamDTO.getDescriptor(),
        }, assigner);
    internal_static_es_encalient_ScoreTableResultDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_encalient_ScoreTableResultDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_es_encalient_ScoreTableResultDTO_descriptor,
        new java.lang.String[] { "Team", "GamesPlayed", "GamesWined", "GamesDrawn", "GamesLost", "ScoreFavor", "ScoreAgainst", "ScoreDifference", "Points", "Position", "League", });
    es.encalient.ProtoTeamDTO.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
