// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LeagueDTO.proto

package es.encalient;

public final class ProtoLeagueDTO {
  private ProtoLeagueDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LeagueDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.encalient.LeagueDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 Id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 Id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string Name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string Name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string Name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 Region = 3;</code>
     *
     * <pre>
     *Either state or region
     * </pre>
     */
    boolean hasRegion();
    /**
     * <code>optional int32 Region = 3;</code>
     *
     * <pre>
     *Either state or region
     * </pre>
     */
    int getRegion();

    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    java.util.List<es.encalient.ProtoTeamDTO.TeamDTO> 
        getTeamsList();
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTO getTeams(int index);
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    int getTeamsCount();
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    java.util.List<? extends es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> 
        getTeamsOrBuilderList();
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeamsOrBuilder(
        int index);

    /**
     * <code>optional string Description = 16;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string Description = 16;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string Description = 16;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string Logo = 17;</code>
     */
    boolean hasLogo();
    /**
     * <code>optional string Logo = 17;</code>
     */
    java.lang.String getLogo();
    /**
     * <code>optional string Logo = 17;</code>
     */
    com.google.protobuf.ByteString
        getLogoBytes();
  }
  /**
   * Protobuf type {@code es.encalient.LeagueDTO}
   */
  public static final class LeagueDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:es.encalient.LeagueDTO)
      LeagueDTOOrBuilder {
    // Use LeagueDTO.newBuilder() to construct.
    private LeagueDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LeagueDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LeagueDTO defaultInstance;
    public static LeagueDTO getDefaultInstance() {
      return defaultInstance;
    }

    public LeagueDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LeagueDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              region_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                teams_ = new java.util.ArrayList<es.encalient.ProtoTeamDTO.TeamDTO>();
                mutable_bitField0_ |= 0x00000008;
              }
              teams_.add(input.readMessage(es.encalient.ProtoTeamDTO.TeamDTO.PARSER, extensionRegistry));
              break;
            }
            case 130: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              description_ = bs;
              break;
            }
            case 138: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              logo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          teams_ = java.util.Collections.unmodifiableList(teams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.encalient.ProtoLeagueDTO.internal_static_es_encalient_LeagueDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.encalient.ProtoLeagueDTO.internal_static_es_encalient_LeagueDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.encalient.ProtoLeagueDTO.LeagueDTO.class, es.encalient.ProtoLeagueDTO.LeagueDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<LeagueDTO> PARSER =
        new com.google.protobuf.AbstractParser<LeagueDTO>() {
      public LeagueDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeagueDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LeagueDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string Name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string Name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_FIELD_NUMBER = 3;
    private int region_;
    /**
     * <code>optional int32 Region = 3;</code>
     *
     * <pre>
     *Either state or region
     * </pre>
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 Region = 3;</code>
     *
     * <pre>
     *Either state or region
     * </pre>
     */
    public int getRegion() {
      return region_;
    }

    public static final int TEAMS_FIELD_NUMBER = 4;
    private java.util.List<es.encalient.ProtoTeamDTO.TeamDTO> teams_;
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    public java.util.List<es.encalient.ProtoTeamDTO.TeamDTO> getTeamsList() {
      return teams_;
    }
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    public java.util.List<? extends es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> 
        getTeamsOrBuilderList() {
      return teams_;
    }
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    public int getTeamsCount() {
      return teams_.size();
    }
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTO getTeams(int index) {
      return teams_.get(index);
    }
    /**
     * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeamsOrBuilder(
        int index) {
      return teams_.get(index);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 16;
    private java.lang.Object description_;
    /**
     * <code>optional string Description = 16;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string Description = 16;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Description = 16;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGO_FIELD_NUMBER = 17;
    private java.lang.Object logo_;
    /**
     * <code>optional string Logo = 17;</code>
     */
    public boolean hasLogo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string Logo = 17;</code>
     */
    public java.lang.String getLogo() {
      java.lang.Object ref = logo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Logo = 17;</code>
     */
    public com.google.protobuf.ByteString
        getLogoBytes() {
      java.lang.Object ref = logo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      name_ = "";
      region_ = 0;
      teams_ = java.util.Collections.emptyList();
      description_ = "";
      logo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, region_);
      }
      for (int i = 0; i < teams_.size(); i++) {
        output.writeMessage(4, teams_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(16, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(17, getLogoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, region_);
      }
      for (int i = 0; i < teams_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, teams_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getLogoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoLeagueDTO.LeagueDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(es.encalient.ProtoLeagueDTO.LeagueDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.encalient.LeagueDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.encalient.LeagueDTO)
        es.encalient.ProtoLeagueDTO.LeagueDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.encalient.ProtoLeagueDTO.internal_static_es_encalient_LeagueDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.encalient.ProtoLeagueDTO.internal_static_es_encalient_LeagueDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.encalient.ProtoLeagueDTO.LeagueDTO.class, es.encalient.ProtoLeagueDTO.LeagueDTO.Builder.class);
      }

      // Construct using es.encalient.ProtoLeagueDTO.LeagueDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTeamsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        region_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          teamsBuilder_.clear();
        }
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        logo_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.encalient.ProtoLeagueDTO.internal_static_es_encalient_LeagueDTO_descriptor;
      }

      public es.encalient.ProtoLeagueDTO.LeagueDTO getDefaultInstanceForType() {
        return es.encalient.ProtoLeagueDTO.LeagueDTO.getDefaultInstance();
      }

      public es.encalient.ProtoLeagueDTO.LeagueDTO build() {
        es.encalient.ProtoLeagueDTO.LeagueDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.encalient.ProtoLeagueDTO.LeagueDTO buildPartial() {
        es.encalient.ProtoLeagueDTO.LeagueDTO result = new es.encalient.ProtoLeagueDTO.LeagueDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.region_ = region_;
        if (teamsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            teams_ = java.util.Collections.unmodifiableList(teams_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.teams_ = teams_;
        } else {
          result.teams_ = teamsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.logo_ = logo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.encalient.ProtoLeagueDTO.LeagueDTO) {
          return mergeFrom((es.encalient.ProtoLeagueDTO.LeagueDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.encalient.ProtoLeagueDTO.LeagueDTO other) {
        if (other == es.encalient.ProtoLeagueDTO.LeagueDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasRegion()) {
          setRegion(other.getRegion());
        }
        if (teamsBuilder_ == null) {
          if (!other.teams_.isEmpty()) {
            if (teams_.isEmpty()) {
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTeamsIsMutable();
              teams_.addAll(other.teams_);
            }
            onChanged();
          }
        } else {
          if (!other.teams_.isEmpty()) {
            if (teamsBuilder_.isEmpty()) {
              teamsBuilder_.dispose();
              teamsBuilder_ = null;
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000008);
              teamsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTeamsFieldBuilder() : null;
            } else {
              teamsBuilder_.addAllMessages(other.teams_);
            }
          }
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000010;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasLogo()) {
          bitField0_ |= 0x00000020;
          logo_ = other.logo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.encalient.ProtoLeagueDTO.LeagueDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.encalient.ProtoLeagueDTO.LeagueDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string Name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string Name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int region_ ;
      /**
       * <code>optional int32 Region = 3;</code>
       *
       * <pre>
       *Either state or region
       * </pre>
       */
      public boolean hasRegion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 Region = 3;</code>
       *
       * <pre>
       *Either state or region
       * </pre>
       */
      public int getRegion() {
        return region_;
      }
      /**
       * <code>optional int32 Region = 3;</code>
       *
       * <pre>
       *Either state or region
       * </pre>
       */
      public Builder setRegion(int value) {
        bitField0_ |= 0x00000004;
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Region = 3;</code>
       *
       * <pre>
       *Either state or region
       * </pre>
       */
      public Builder clearRegion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        region_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<es.encalient.ProtoTeamDTO.TeamDTO> teams_ =
        java.util.Collections.emptyList();
      private void ensureTeamsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          teams_ = new java.util.ArrayList<es.encalient.ProtoTeamDTO.TeamDTO>(teams_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> teamsBuilder_;

      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public java.util.List<es.encalient.ProtoTeamDTO.TeamDTO> getTeamsList() {
        if (teamsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teams_);
        } else {
          return teamsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public int getTeamsCount() {
        if (teamsBuilder_ == null) {
          return teams_.size();
        } else {
          return teamsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO getTeams(int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);
        } else {
          return teamsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder setTeams(
          int index, es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.set(index, value);
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder setTeams(
          int index, es.encalient.ProtoTeamDTO.TeamDTO.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.set(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder addTeams(es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder addTeams(
          int index, es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(index, value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder addTeams(
          es.encalient.ProtoTeamDTO.TeamDTO.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder addTeams(
          int index, es.encalient.ProtoTeamDTO.TeamDTO.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder addAllTeams(
          java.lang.Iterable<? extends es.encalient.ProtoTeamDTO.TeamDTO> values) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teams_);
          onChanged();
        } else {
          teamsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder clearTeams() {
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          teamsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public Builder removeTeams(int index) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.remove(index);
          onChanged();
        } else {
          teamsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO.Builder getTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeamsOrBuilder(
          int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);  } else {
          return teamsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public java.util.List<? extends es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> 
           getTeamsOrBuilderList() {
        if (teamsBuilder_ != null) {
          return teamsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teams_);
        }
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO.Builder addTeamsBuilder() {
        return getTeamsFieldBuilder().addBuilder(
            es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO.Builder addTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().addBuilder(
            index, es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.TeamDTO teams = 4;</code>
       */
      public java.util.List<es.encalient.ProtoTeamDTO.TeamDTO.Builder> 
           getTeamsBuilderList() {
        return getTeamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> 
          getTeamsFieldBuilder() {
        if (teamsBuilder_ == null) {
          teamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder>(
                  teams_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          teams_ = null;
        }
        return teamsBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string Description = 16;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000010);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Description = 16;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logo_ = "";
      /**
       * <code>optional string Logo = 17;</code>
       */
      public boolean hasLogo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string Logo = 17;</code>
       */
      public java.lang.String getLogo() {
        java.lang.Object ref = logo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            logo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Logo = 17;</code>
       */
      public com.google.protobuf.ByteString
          getLogoBytes() {
        java.lang.Object ref = logo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Logo = 17;</code>
       */
      public Builder setLogo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        logo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Logo = 17;</code>
       */
      public Builder clearLogo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        logo_ = getDefaultInstance().getLogo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Logo = 17;</code>
       */
      public Builder setLogoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        logo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:es.encalient.LeagueDTO)
    }

    static {
      defaultInstance = new LeagueDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:es.encalient.LeagueDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_encalient_LeagueDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_es_encalient_LeagueDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017LeagueDTO.proto\022\014es.encalient\032\rTeamDTO" +
      ".proto\"~\n\tLeagueDTO\022\n\n\002Id\030\001 \001(\003\022\014\n\004Name\030" +
      "\002 \001(\t\022\016\n\006Region\030\003 \001(\005\022$\n\005teams\030\004 \003(\0132\025.e" +
      "s.encalient.TeamDTO\022\023\n\013Description\030\020 \001(\t" +
      "\022\014\n\004Logo\030\021 \001(\tB\020B\016ProtoLeagueDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          es.encalient.ProtoTeamDTO.getDescriptor(),
        }, assigner);
    internal_static_es_encalient_LeagueDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_encalient_LeagueDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_es_encalient_LeagueDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Region", "Teams", "Description", "Logo", });
    es.encalient.ProtoTeamDTO.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
