// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MatchDTO.proto

package es.encalient;

public final class ProtoMatchDTO {
  private ProtoMatchDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MatchDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.encalient.MatchDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 Id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 Id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string Date = 2;</code>
     */
    boolean hasDate();
    /**
     * <code>optional string Date = 2;</code>
     */
    java.lang.String getDate();
    /**
     * <code>optional string Date = 2;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>optional .es.encalient.FieldDTO Field = 3;</code>
     */
    boolean hasField();
    /**
     * <code>optional .es.encalient.FieldDTO Field = 3;</code>
     */
    es.encalient.ProtoFieldDTO.FieldDTO getField();
    /**
     * <code>optional .es.encalient.FieldDTO Field = 3;</code>
     */
    es.encalient.ProtoFieldDTO.FieldDTOOrBuilder getFieldOrBuilder();

    /**
     * <code>optional string Details = 19;</code>
     */
    boolean hasDetails();
    /**
     * <code>optional string Details = 19;</code>
     */
    java.lang.String getDetails();
    /**
     * <code>optional string Details = 19;</code>
     */
    com.google.protobuf.ByteString
        getDetailsBytes();

    /**
     * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
     */
    boolean hasTeam1();
    /**
     * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTO getTeam1();
    /**
     * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeam1OrBuilder();

    /**
     * <code>optional int64 ScoreTeam1 = 5;</code>
     */
    boolean hasScoreTeam1();
    /**
     * <code>optional int64 ScoreTeam1 = 5;</code>
     */
    long getScoreTeam1();

    /**
     * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
     */
    boolean hasScoreExtraTimeTeam1();
    /**
     * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
     */
    long getScoreExtraTimeTeam1();

    /**
     * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
     */
    boolean hasTeam2();
    /**
     * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTO getTeam2();
    /**
     * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
     */
    es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeam2OrBuilder();

    /**
     * <code>optional int64 ScoreTeam2 = 7;</code>
     */
    boolean hasScoreTeam2();
    /**
     * <code>optional int64 ScoreTeam2 = 7;</code>
     */
    long getScoreTeam2();

    /**
     * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
     */
    boolean hasScoreExtraTimeTeam2();
    /**
     * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
     */
    long getScoreExtraTimeTeam2();

    /**
     * <code>optional bool Finished = 8;</code>
     */
    boolean hasFinished();
    /**
     * <code>optional bool Finished = 8;</code>
     */
    boolean getFinished();

    /**
     * <code>optional bool Forfeit = 9;</code>
     */
    boolean hasForfeit();
    /**
     * <code>optional bool Forfeit = 9;</code>
     */
    boolean getForfeit();
  }
  /**
   * Protobuf type {@code es.encalient.MatchDTO}
   */
  public static final class MatchDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:es.encalient.MatchDTO)
      MatchDTOOrBuilder {
    // Use MatchDTO.newBuilder() to construct.
    private MatchDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatchDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatchDTO defaultInstance;
    public static MatchDTO getDefaultInstance() {
      return defaultInstance;
    }

    public MatchDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatchDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              date_ = bs;
              break;
            }
            case 26: {
              es.encalient.ProtoFieldDTO.FieldDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = field_.toBuilder();
              }
              field_ = input.readMessage(es.encalient.ProtoFieldDTO.FieldDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(field_);
                field_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              es.encalient.ProtoTeamDTO.TeamDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = team1_.toBuilder();
              }
              team1_ = input.readMessage(es.encalient.ProtoTeamDTO.TeamDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(team1_);
                team1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000020;
              scoreTeam1_ = input.readInt64();
              break;
            }
            case 50: {
              es.encalient.ProtoTeamDTO.TeamDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = team2_.toBuilder();
              }
              team2_ = input.readMessage(es.encalient.ProtoTeamDTO.TeamDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(team2_);
                team2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000100;
              scoreTeam2_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000400;
              finished_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000800;
              forfeit_ = input.readBool();
              break;
            }
            case 154: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              details_ = bs;
              break;
            }
            case 160: {
              bitField0_ |= 0x00000040;
              scoreExtraTimeTeam1_ = input.readInt64();
              break;
            }
            case 176: {
              bitField0_ |= 0x00000200;
              scoreExtraTimeTeam2_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.encalient.ProtoMatchDTO.internal_static_es_encalient_MatchDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.encalient.ProtoMatchDTO.internal_static_es_encalient_MatchDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.encalient.ProtoMatchDTO.MatchDTO.class, es.encalient.ProtoMatchDTO.MatchDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<MatchDTO> PARSER =
        new com.google.protobuf.AbstractParser<MatchDTO>() {
      public MatchDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatchDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private java.lang.Object date_;
    /**
     * <code>optional string Date = 2;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string Date = 2;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD_FIELD_NUMBER = 3;
    private es.encalient.ProtoFieldDTO.FieldDTO field_;
    /**
     * <code>optional .es.encalient.FieldDTO Field = 3;</code>
     */
    public boolean hasField() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .es.encalient.FieldDTO Field = 3;</code>
     */
    public es.encalient.ProtoFieldDTO.FieldDTO getField() {
      return field_;
    }
    /**
     * <code>optional .es.encalient.FieldDTO Field = 3;</code>
     */
    public es.encalient.ProtoFieldDTO.FieldDTOOrBuilder getFieldOrBuilder() {
      return field_;
    }

    public static final int DETAILS_FIELD_NUMBER = 19;
    private java.lang.Object details_;
    /**
     * <code>optional string Details = 19;</code>
     */
    public boolean hasDetails() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string Details = 19;</code>
     */
    public java.lang.String getDetails() {
      java.lang.Object ref = details_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          details_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Details = 19;</code>
     */
    public com.google.protobuf.ByteString
        getDetailsBytes() {
      java.lang.Object ref = details_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        details_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEAM1_FIELD_NUMBER = 4;
    private es.encalient.ProtoTeamDTO.TeamDTO team1_;
    /**
     * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
     */
    public boolean hasTeam1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTO getTeam1() {
      return team1_;
    }
    /**
     * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeam1OrBuilder() {
      return team1_;
    }

    public static final int SCORETEAM1_FIELD_NUMBER = 5;
    private long scoreTeam1_;
    /**
     * <code>optional int64 ScoreTeam1 = 5;</code>
     */
    public boolean hasScoreTeam1() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 ScoreTeam1 = 5;</code>
     */
    public long getScoreTeam1() {
      return scoreTeam1_;
    }

    public static final int SCOREEXTRATIMETEAM1_FIELD_NUMBER = 20;
    private long scoreExtraTimeTeam1_;
    /**
     * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
     */
    public boolean hasScoreExtraTimeTeam1() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
     */
    public long getScoreExtraTimeTeam1() {
      return scoreExtraTimeTeam1_;
    }

    public static final int TEAM2_FIELD_NUMBER = 6;
    private es.encalient.ProtoTeamDTO.TeamDTO team2_;
    /**
     * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
     */
    public boolean hasTeam2() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTO getTeam2() {
      return team2_;
    }
    /**
     * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
     */
    public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeam2OrBuilder() {
      return team2_;
    }

    public static final int SCORETEAM2_FIELD_NUMBER = 7;
    private long scoreTeam2_;
    /**
     * <code>optional int64 ScoreTeam2 = 7;</code>
     */
    public boolean hasScoreTeam2() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 ScoreTeam2 = 7;</code>
     */
    public long getScoreTeam2() {
      return scoreTeam2_;
    }

    public static final int SCOREEXTRATIMETEAM2_FIELD_NUMBER = 22;
    private long scoreExtraTimeTeam2_;
    /**
     * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
     */
    public boolean hasScoreExtraTimeTeam2() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
     */
    public long getScoreExtraTimeTeam2() {
      return scoreExtraTimeTeam2_;
    }

    public static final int FINISHED_FIELD_NUMBER = 8;
    private boolean finished_;
    /**
     * <code>optional bool Finished = 8;</code>
     */
    public boolean hasFinished() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional bool Finished = 8;</code>
     */
    public boolean getFinished() {
      return finished_;
    }

    public static final int FORFEIT_FIELD_NUMBER = 9;
    private boolean forfeit_;
    /**
     * <code>optional bool Forfeit = 9;</code>
     */
    public boolean hasForfeit() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional bool Forfeit = 9;</code>
     */
    public boolean getForfeit() {
      return forfeit_;
    }

    private void initFields() {
      id_ = 0L;
      date_ = "";
      field_ = es.encalient.ProtoFieldDTO.FieldDTO.getDefaultInstance();
      details_ = "";
      team1_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
      scoreTeam1_ = 0L;
      scoreExtraTimeTeam1_ = 0L;
      team2_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
      scoreTeam2_ = 0L;
      scoreExtraTimeTeam2_ = 0L;
      finished_ = false;
      forfeit_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, field_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(4, team1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(5, scoreTeam1_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(6, team2_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(7, scoreTeam2_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBool(8, finished_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBool(9, forfeit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(19, getDetailsBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(20, scoreExtraTimeTeam1_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(22, scoreExtraTimeTeam2_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, field_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, team1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, scoreTeam1_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, team2_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, scoreTeam2_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, finished_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, forfeit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(19, getDetailsBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(20, scoreExtraTimeTeam1_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(22, scoreExtraTimeTeam2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoMatchDTO.MatchDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(es.encalient.ProtoMatchDTO.MatchDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.encalient.MatchDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.encalient.MatchDTO)
        es.encalient.ProtoMatchDTO.MatchDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.encalient.ProtoMatchDTO.internal_static_es_encalient_MatchDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.encalient.ProtoMatchDTO.internal_static_es_encalient_MatchDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.encalient.ProtoMatchDTO.MatchDTO.class, es.encalient.ProtoMatchDTO.MatchDTO.Builder.class);
      }

      // Construct using es.encalient.ProtoMatchDTO.MatchDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFieldFieldBuilder();
          getTeam1FieldBuilder();
          getTeam2FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fieldBuilder_ == null) {
          field_ = es.encalient.ProtoFieldDTO.FieldDTO.getDefaultInstance();
        } else {
          fieldBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        details_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (team1Builder_ == null) {
          team1_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
        } else {
          team1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        scoreTeam1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        scoreExtraTimeTeam1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (team2Builder_ == null) {
          team2_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
        } else {
          team2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        scoreTeam2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        scoreExtraTimeTeam2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        finished_ = false;
        bitField0_ = (bitField0_ & ~0x00000400);
        forfeit_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.encalient.ProtoMatchDTO.internal_static_es_encalient_MatchDTO_descriptor;
      }

      public es.encalient.ProtoMatchDTO.MatchDTO getDefaultInstanceForType() {
        return es.encalient.ProtoMatchDTO.MatchDTO.getDefaultInstance();
      }

      public es.encalient.ProtoMatchDTO.MatchDTO build() {
        es.encalient.ProtoMatchDTO.MatchDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.encalient.ProtoMatchDTO.MatchDTO buildPartial() {
        es.encalient.ProtoMatchDTO.MatchDTO result = new es.encalient.ProtoMatchDTO.MatchDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (fieldBuilder_ == null) {
          result.field_ = field_;
        } else {
          result.field_ = fieldBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.details_ = details_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (team1Builder_ == null) {
          result.team1_ = team1_;
        } else {
          result.team1_ = team1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.scoreTeam1_ = scoreTeam1_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.scoreExtraTimeTeam1_ = scoreExtraTimeTeam1_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (team2Builder_ == null) {
          result.team2_ = team2_;
        } else {
          result.team2_ = team2Builder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.scoreTeam2_ = scoreTeam2_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.scoreExtraTimeTeam2_ = scoreExtraTimeTeam2_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.finished_ = finished_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.forfeit_ = forfeit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.encalient.ProtoMatchDTO.MatchDTO) {
          return mergeFrom((es.encalient.ProtoMatchDTO.MatchDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.encalient.ProtoMatchDTO.MatchDTO other) {
        if (other == es.encalient.ProtoMatchDTO.MatchDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000002;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasField()) {
          mergeField(other.getField());
        }
        if (other.hasDetails()) {
          bitField0_ |= 0x00000008;
          details_ = other.details_;
          onChanged();
        }
        if (other.hasTeam1()) {
          mergeTeam1(other.getTeam1());
        }
        if (other.hasScoreTeam1()) {
          setScoreTeam1(other.getScoreTeam1());
        }
        if (other.hasScoreExtraTimeTeam1()) {
          setScoreExtraTimeTeam1(other.getScoreExtraTimeTeam1());
        }
        if (other.hasTeam2()) {
          mergeTeam2(other.getTeam2());
        }
        if (other.hasScoreTeam2()) {
          setScoreTeam2(other.getScoreTeam2());
        }
        if (other.hasScoreExtraTimeTeam2()) {
          setScoreExtraTimeTeam2(other.getScoreExtraTimeTeam2());
        }
        if (other.hasFinished()) {
          setFinished(other.getFinished());
        }
        if (other.hasForfeit()) {
          setForfeit(other.getForfeit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.encalient.ProtoMatchDTO.MatchDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.encalient.ProtoMatchDTO.MatchDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>optional string Date = 2;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }

      private es.encalient.ProtoFieldDTO.FieldDTO field_ = es.encalient.ProtoFieldDTO.FieldDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoFieldDTO.FieldDTO, es.encalient.ProtoFieldDTO.FieldDTO.Builder, es.encalient.ProtoFieldDTO.FieldDTOOrBuilder> fieldBuilder_;
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public boolean hasField() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public es.encalient.ProtoFieldDTO.FieldDTO getField() {
        if (fieldBuilder_ == null) {
          return field_;
        } else {
          return fieldBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public Builder setField(es.encalient.ProtoFieldDTO.FieldDTO value) {
        if (fieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field_ = value;
          onChanged();
        } else {
          fieldBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public Builder setField(
          es.encalient.ProtoFieldDTO.FieldDTO.Builder builderForValue) {
        if (fieldBuilder_ == null) {
          field_ = builderForValue.build();
          onChanged();
        } else {
          fieldBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public Builder mergeField(es.encalient.ProtoFieldDTO.FieldDTO value) {
        if (fieldBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              field_ != es.encalient.ProtoFieldDTO.FieldDTO.getDefaultInstance()) {
            field_ =
              es.encalient.ProtoFieldDTO.FieldDTO.newBuilder(field_).mergeFrom(value).buildPartial();
          } else {
            field_ = value;
          }
          onChanged();
        } else {
          fieldBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public Builder clearField() {
        if (fieldBuilder_ == null) {
          field_ = es.encalient.ProtoFieldDTO.FieldDTO.getDefaultInstance();
          onChanged();
        } else {
          fieldBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public es.encalient.ProtoFieldDTO.FieldDTO.Builder getFieldBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFieldFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      public es.encalient.ProtoFieldDTO.FieldDTOOrBuilder getFieldOrBuilder() {
        if (fieldBuilder_ != null) {
          return fieldBuilder_.getMessageOrBuilder();
        } else {
          return field_;
        }
      }
      /**
       * <code>optional .es.encalient.FieldDTO Field = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoFieldDTO.FieldDTO, es.encalient.ProtoFieldDTO.FieldDTO.Builder, es.encalient.ProtoFieldDTO.FieldDTOOrBuilder> 
          getFieldFieldBuilder() {
        if (fieldBuilder_ == null) {
          fieldBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              es.encalient.ProtoFieldDTO.FieldDTO, es.encalient.ProtoFieldDTO.FieldDTO.Builder, es.encalient.ProtoFieldDTO.FieldDTOOrBuilder>(
                  getField(),
                  getParentForChildren(),
                  isClean());
          field_ = null;
        }
        return fieldBuilder_;
      }

      private java.lang.Object details_ = "";
      /**
       * <code>optional string Details = 19;</code>
       */
      public boolean hasDetails() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string Details = 19;</code>
       */
      public java.lang.String getDetails() {
        java.lang.Object ref = details_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            details_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Details = 19;</code>
       */
      public com.google.protobuf.ByteString
          getDetailsBytes() {
        java.lang.Object ref = details_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          details_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Details = 19;</code>
       */
      public Builder setDetails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        details_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Details = 19;</code>
       */
      public Builder clearDetails() {
        bitField0_ = (bitField0_ & ~0x00000008);
        details_ = getDefaultInstance().getDetails();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Details = 19;</code>
       */
      public Builder setDetailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        details_ = value;
        onChanged();
        return this;
      }

      private es.encalient.ProtoTeamDTO.TeamDTO team1_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> team1Builder_;
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public boolean hasTeam1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO getTeam1() {
        if (team1Builder_ == null) {
          return team1_;
        } else {
          return team1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public Builder setTeam1(es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (team1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          team1_ = value;
          onChanged();
        } else {
          team1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public Builder setTeam1(
          es.encalient.ProtoTeamDTO.TeamDTO.Builder builderForValue) {
        if (team1Builder_ == null) {
          team1_ = builderForValue.build();
          onChanged();
        } else {
          team1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public Builder mergeTeam1(es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (team1Builder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              team1_ != es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance()) {
            team1_ =
              es.encalient.ProtoTeamDTO.TeamDTO.newBuilder(team1_).mergeFrom(value).buildPartial();
          } else {
            team1_ = value;
          }
          onChanged();
        } else {
          team1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public Builder clearTeam1() {
        if (team1Builder_ == null) {
          team1_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
          onChanged();
        } else {
          team1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO.Builder getTeam1Builder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getTeam1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeam1OrBuilder() {
        if (team1Builder_ != null) {
          return team1Builder_.getMessageOrBuilder();
        } else {
          return team1_;
        }
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team1 = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> 
          getTeam1FieldBuilder() {
        if (team1Builder_ == null) {
          team1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder>(
                  getTeam1(),
                  getParentForChildren(),
                  isClean());
          team1_ = null;
        }
        return team1Builder_;
      }

      private long scoreTeam1_ ;
      /**
       * <code>optional int64 ScoreTeam1 = 5;</code>
       */
      public boolean hasScoreTeam1() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 ScoreTeam1 = 5;</code>
       */
      public long getScoreTeam1() {
        return scoreTeam1_;
      }
      /**
       * <code>optional int64 ScoreTeam1 = 5;</code>
       */
      public Builder setScoreTeam1(long value) {
        bitField0_ |= 0x00000020;
        scoreTeam1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ScoreTeam1 = 5;</code>
       */
      public Builder clearScoreTeam1() {
        bitField0_ = (bitField0_ & ~0x00000020);
        scoreTeam1_ = 0L;
        onChanged();
        return this;
      }

      private long scoreExtraTimeTeam1_ ;
      /**
       * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
       */
      public boolean hasScoreExtraTimeTeam1() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
       */
      public long getScoreExtraTimeTeam1() {
        return scoreExtraTimeTeam1_;
      }
      /**
       * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
       */
      public Builder setScoreExtraTimeTeam1(long value) {
        bitField0_ |= 0x00000040;
        scoreExtraTimeTeam1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ScoreExtraTimeTeam1 = 20;</code>
       */
      public Builder clearScoreExtraTimeTeam1() {
        bitField0_ = (bitField0_ & ~0x00000040);
        scoreExtraTimeTeam1_ = 0L;
        onChanged();
        return this;
      }

      private es.encalient.ProtoTeamDTO.TeamDTO team2_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> team2Builder_;
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public boolean hasTeam2() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO getTeam2() {
        if (team2Builder_ == null) {
          return team2_;
        } else {
          return team2Builder_.getMessage();
        }
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public Builder setTeam2(es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (team2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          team2_ = value;
          onChanged();
        } else {
          team2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public Builder setTeam2(
          es.encalient.ProtoTeamDTO.TeamDTO.Builder builderForValue) {
        if (team2Builder_ == null) {
          team2_ = builderForValue.build();
          onChanged();
        } else {
          team2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public Builder mergeTeam2(es.encalient.ProtoTeamDTO.TeamDTO value) {
        if (team2Builder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              team2_ != es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance()) {
            team2_ =
              es.encalient.ProtoTeamDTO.TeamDTO.newBuilder(team2_).mergeFrom(value).buildPartial();
          } else {
            team2_ = value;
          }
          onChanged();
        } else {
          team2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public Builder clearTeam2() {
        if (team2Builder_ == null) {
          team2_ = es.encalient.ProtoTeamDTO.TeamDTO.getDefaultInstance();
          onChanged();
        } else {
          team2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTO.Builder getTeam2Builder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getTeam2FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      public es.encalient.ProtoTeamDTO.TeamDTOOrBuilder getTeam2OrBuilder() {
        if (team2Builder_ != null) {
          return team2Builder_.getMessageOrBuilder();
        } else {
          return team2_;
        }
      }
      /**
       * <code>optional .es.encalient.TeamDTO Team2 = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder> 
          getTeam2FieldBuilder() {
        if (team2Builder_ == null) {
          team2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              es.encalient.ProtoTeamDTO.TeamDTO, es.encalient.ProtoTeamDTO.TeamDTO.Builder, es.encalient.ProtoTeamDTO.TeamDTOOrBuilder>(
                  getTeam2(),
                  getParentForChildren(),
                  isClean());
          team2_ = null;
        }
        return team2Builder_;
      }

      private long scoreTeam2_ ;
      /**
       * <code>optional int64 ScoreTeam2 = 7;</code>
       */
      public boolean hasScoreTeam2() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 ScoreTeam2 = 7;</code>
       */
      public long getScoreTeam2() {
        return scoreTeam2_;
      }
      /**
       * <code>optional int64 ScoreTeam2 = 7;</code>
       */
      public Builder setScoreTeam2(long value) {
        bitField0_ |= 0x00000100;
        scoreTeam2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ScoreTeam2 = 7;</code>
       */
      public Builder clearScoreTeam2() {
        bitField0_ = (bitField0_ & ~0x00000100);
        scoreTeam2_ = 0L;
        onChanged();
        return this;
      }

      private long scoreExtraTimeTeam2_ ;
      /**
       * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
       */
      public boolean hasScoreExtraTimeTeam2() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
       */
      public long getScoreExtraTimeTeam2() {
        return scoreExtraTimeTeam2_;
      }
      /**
       * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
       */
      public Builder setScoreExtraTimeTeam2(long value) {
        bitField0_ |= 0x00000200;
        scoreExtraTimeTeam2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ScoreExtraTimeTeam2 = 22;</code>
       */
      public Builder clearScoreExtraTimeTeam2() {
        bitField0_ = (bitField0_ & ~0x00000200);
        scoreExtraTimeTeam2_ = 0L;
        onChanged();
        return this;
      }

      private boolean finished_ ;
      /**
       * <code>optional bool Finished = 8;</code>
       */
      public boolean hasFinished() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional bool Finished = 8;</code>
       */
      public boolean getFinished() {
        return finished_;
      }
      /**
       * <code>optional bool Finished = 8;</code>
       */
      public Builder setFinished(boolean value) {
        bitField0_ |= 0x00000400;
        finished_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Finished = 8;</code>
       */
      public Builder clearFinished() {
        bitField0_ = (bitField0_ & ~0x00000400);
        finished_ = false;
        onChanged();
        return this;
      }

      private boolean forfeit_ ;
      /**
       * <code>optional bool Forfeit = 9;</code>
       */
      public boolean hasForfeit() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bool Forfeit = 9;</code>
       */
      public boolean getForfeit() {
        return forfeit_;
      }
      /**
       * <code>optional bool Forfeit = 9;</code>
       */
      public Builder setForfeit(boolean value) {
        bitField0_ |= 0x00000800;
        forfeit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Forfeit = 9;</code>
       */
      public Builder clearForfeit() {
        bitField0_ = (bitField0_ & ~0x00000800);
        forfeit_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:es.encalient.MatchDTO)
    }

    static {
      defaultInstance = new MatchDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:es.encalient.MatchDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_encalient_MatchDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_es_encalient_MatchDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MatchDTO.proto\022\014es.encalient\032\016FieldDTO" +
      ".proto\032\rTeamDTO.proto\"\255\002\n\010MatchDTO\022\n\n\002Id" +
      "\030\001 \001(\003\022\014\n\004Date\030\002 \001(\t\022%\n\005Field\030\003 \001(\0132\026.es" +
      ".encalient.FieldDTO\022\017\n\007Details\030\023 \001(\t\022$\n\005" +
      "Team1\030\004 \001(\0132\025.es.encalient.TeamDTO\022\022\n\nSc" +
      "oreTeam1\030\005 \001(\003\022\033\n\023ScoreExtraTimeTeam1\030\024 " +
      "\001(\003\022$\n\005Team2\030\006 \001(\0132\025.es.encalient.TeamDT" +
      "O\022\022\n\nScoreTeam2\030\007 \001(\003\022\033\n\023ScoreExtraTimeT" +
      "eam2\030\026 \001(\003\022\020\n\010Finished\030\010 \001(\010\022\017\n\007Forfeit\030" +
      "\t \001(\010B\017B\rProtoMatchDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          es.encalient.ProtoFieldDTO.getDescriptor(),
          es.encalient.ProtoTeamDTO.getDescriptor(),
        }, assigner);
    internal_static_es_encalient_MatchDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_encalient_MatchDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_es_encalient_MatchDTO_descriptor,
        new java.lang.String[] { "Id", "Date", "Field", "Details", "Team1", "ScoreTeam1", "ScoreExtraTimeTeam1", "Team2", "ScoreTeam2", "ScoreExtraTimeTeam2", "Finished", "Forfeit", });
    es.encalient.ProtoFieldDTO.getDescriptor();
    es.encalient.ProtoTeamDTO.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
