// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeekDTO.proto

package es.encalient;

public final class ProtoWeekDTO {
  private ProtoWeekDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WeekDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.encalient.WeekDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 Id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 Id = 1;</code>
     */
    long getId();

    /**
     * <code>optional int64 Season = 2;</code>
     */
    boolean hasSeason();
    /**
     * <code>optional int64 Season = 2;</code>
     */
    long getSeason();

    /**
     * <code>optional string Title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string Title = 3;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string Title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string Description = 4;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string Description = 4;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string Description = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string DateFrom = 5;</code>
     */
    boolean hasDateFrom();
    /**
     * <code>optional string DateFrom = 5;</code>
     */
    java.lang.String getDateFrom();
    /**
     * <code>optional string DateFrom = 5;</code>
     */
    com.google.protobuf.ByteString
        getDateFromBytes();

    /**
     * <code>optional string DateTo = 6;</code>
     */
    boolean hasDateTo();
    /**
     * <code>optional string DateTo = 6;</code>
     */
    java.lang.String getDateTo();
    /**
     * <code>optional string DateTo = 6;</code>
     */
    com.google.protobuf.ByteString
        getDateToBytes();

    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    java.util.List<es.encalient.ProtoMatchDTO.MatchDTO> 
        getMatchesList();
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    es.encalient.ProtoMatchDTO.MatchDTO getMatches(int index);
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    int getMatchesCount();
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    java.util.List<? extends es.encalient.ProtoMatchDTO.MatchDTOOrBuilder> 
        getMatchesOrBuilderList();
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    es.encalient.ProtoMatchDTO.MatchDTOOrBuilder getMatchesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code es.encalient.WeekDTO}
   */
  public static final class WeekDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:es.encalient.WeekDTO)
      WeekDTOOrBuilder {
    // Use WeekDTO.newBuilder() to construct.
    private WeekDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WeekDTO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WeekDTO defaultInstance;
    public static WeekDTO getDefaultInstance() {
      return defaultInstance;
    }

    public WeekDTO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WeekDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              season_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              title_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              description_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              dateFrom_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              dateTo_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                matches_ = new java.util.ArrayList<es.encalient.ProtoMatchDTO.MatchDTO>();
                mutable_bitField0_ |= 0x00000040;
              }
              matches_.add(input.readMessage(es.encalient.ProtoMatchDTO.MatchDTO.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          matches_ = java.util.Collections.unmodifiableList(matches_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.encalient.ProtoWeekDTO.internal_static_es_encalient_WeekDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.encalient.ProtoWeekDTO.internal_static_es_encalient_WeekDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.encalient.ProtoWeekDTO.WeekDTO.class, es.encalient.ProtoWeekDTO.WeekDTO.Builder.class);
    }

    public static com.google.protobuf.Parser<WeekDTO> PARSER =
        new com.google.protobuf.AbstractParser<WeekDTO>() {
      public WeekDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeekDTO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WeekDTO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 Id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int SEASON_FIELD_NUMBER = 2;
    private long season_;
    /**
     * <code>optional int64 Season = 2;</code>
     */
    public boolean hasSeason() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 Season = 2;</code>
     */
    public long getSeason() {
      return season_;
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    /**
     * <code>optional string Title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string Title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private java.lang.Object description_;
    /**
     * <code>optional string Description = 4;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string Description = 4;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATEFROM_FIELD_NUMBER = 5;
    private java.lang.Object dateFrom_;
    /**
     * <code>optional string DateFrom = 5;</code>
     */
    public boolean hasDateFrom() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string DateFrom = 5;</code>
     */
    public java.lang.String getDateFrom() {
      java.lang.Object ref = dateFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dateFrom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string DateFrom = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDateFromBytes() {
      java.lang.Object ref = dateFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATETO_FIELD_NUMBER = 6;
    private java.lang.Object dateTo_;
    /**
     * <code>optional string DateTo = 6;</code>
     */
    public boolean hasDateTo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string DateTo = 6;</code>
     */
    public java.lang.String getDateTo() {
      java.lang.Object ref = dateTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dateTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string DateTo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDateToBytes() {
      java.lang.Object ref = dateTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHES_FIELD_NUMBER = 7;
    private java.util.List<es.encalient.ProtoMatchDTO.MatchDTO> matches_;
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    public java.util.List<es.encalient.ProtoMatchDTO.MatchDTO> getMatchesList() {
      return matches_;
    }
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    public java.util.List<? extends es.encalient.ProtoMatchDTO.MatchDTOOrBuilder> 
        getMatchesOrBuilderList() {
      return matches_;
    }
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    public int getMatchesCount() {
      return matches_.size();
    }
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    public es.encalient.ProtoMatchDTO.MatchDTO getMatches(int index) {
      return matches_.get(index);
    }
    /**
     * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
     */
    public es.encalient.ProtoMatchDTO.MatchDTOOrBuilder getMatchesOrBuilder(
        int index) {
      return matches_.get(index);
    }

    private void initFields() {
      id_ = 0L;
      season_ = 0L;
      title_ = "";
      description_ = "";
      dateFrom_ = "";
      dateTo_ = "";
      matches_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, season_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDateFromBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDateToBytes());
      }
      for (int i = 0; i < matches_.size(); i++) {
        output.writeMessage(7, matches_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, season_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDateFromBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDateToBytes());
      }
      for (int i = 0; i < matches_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, matches_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static es.encalient.ProtoWeekDTO.WeekDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(es.encalient.ProtoWeekDTO.WeekDTO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.encalient.WeekDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.encalient.WeekDTO)
        es.encalient.ProtoWeekDTO.WeekDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.encalient.ProtoWeekDTO.internal_static_es_encalient_WeekDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.encalient.ProtoWeekDTO.internal_static_es_encalient_WeekDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.encalient.ProtoWeekDTO.WeekDTO.class, es.encalient.ProtoWeekDTO.WeekDTO.Builder.class);
      }

      // Construct using es.encalient.ProtoWeekDTO.WeekDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMatchesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        season_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dateFrom_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        dateTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.encalient.ProtoWeekDTO.internal_static_es_encalient_WeekDTO_descriptor;
      }

      public es.encalient.ProtoWeekDTO.WeekDTO getDefaultInstanceForType() {
        return es.encalient.ProtoWeekDTO.WeekDTO.getDefaultInstance();
      }

      public es.encalient.ProtoWeekDTO.WeekDTO build() {
        es.encalient.ProtoWeekDTO.WeekDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.encalient.ProtoWeekDTO.WeekDTO buildPartial() {
        es.encalient.ProtoWeekDTO.WeekDTO result = new es.encalient.ProtoWeekDTO.WeekDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.season_ = season_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dateFrom_ = dateFrom_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.dateTo_ = dateTo_;
        if (matchesBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            matches_ = java.util.Collections.unmodifiableList(matches_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.matches_ = matches_;
        } else {
          result.matches_ = matchesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.encalient.ProtoWeekDTO.WeekDTO) {
          return mergeFrom((es.encalient.ProtoWeekDTO.WeekDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.encalient.ProtoWeekDTO.WeekDTO other) {
        if (other == es.encalient.ProtoWeekDTO.WeekDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSeason()) {
          setSeason(other.getSeason());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000004;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000008;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasDateFrom()) {
          bitField0_ |= 0x00000010;
          dateFrom_ = other.dateFrom_;
          onChanged();
        }
        if (other.hasDateTo()) {
          bitField0_ |= 0x00000020;
          dateTo_ = other.dateTo_;
          onChanged();
        }
        if (matchesBuilder_ == null) {
          if (!other.matches_.isEmpty()) {
            if (matches_.isEmpty()) {
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureMatchesIsMutable();
              matches_.addAll(other.matches_);
            }
            onChanged();
          }
        } else {
          if (!other.matches_.isEmpty()) {
            if (matchesBuilder_.isEmpty()) {
              matchesBuilder_.dispose();
              matchesBuilder_ = null;
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000040);
              matchesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMatchesFieldBuilder() : null;
            } else {
              matchesBuilder_.addAllMessages(other.matches_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.encalient.ProtoWeekDTO.WeekDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.encalient.ProtoWeekDTO.WeekDTO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long season_ ;
      /**
       * <code>optional int64 Season = 2;</code>
       */
      public boolean hasSeason() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 Season = 2;</code>
       */
      public long getSeason() {
        return season_;
      }
      /**
       * <code>optional int64 Season = 2;</code>
       */
      public Builder setSeason(long value) {
        bitField0_ |= 0x00000002;
        season_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Season = 2;</code>
       */
      public Builder clearSeason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        season_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string Title = 3;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string Description = 4;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string Description = 4;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Description = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Description = 4;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Description = 4;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Description = 4;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateFrom_ = "";
      /**
       * <code>optional string DateFrom = 5;</code>
       */
      public boolean hasDateFrom() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string DateFrom = 5;</code>
       */
      public java.lang.String getDateFrom() {
        java.lang.Object ref = dateFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dateFrom_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string DateFrom = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDateFromBytes() {
        java.lang.Object ref = dateFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string DateFrom = 5;</code>
       */
      public Builder setDateFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dateFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateFrom = 5;</code>
       */
      public Builder clearDateFrom() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dateFrom_ = getDefaultInstance().getDateFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateFrom = 5;</code>
       */
      public Builder setDateFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dateFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateTo_ = "";
      /**
       * <code>optional string DateTo = 6;</code>
       */
      public boolean hasDateTo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string DateTo = 6;</code>
       */
      public java.lang.String getDateTo() {
        java.lang.Object ref = dateTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dateTo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string DateTo = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDateToBytes() {
        java.lang.Object ref = dateTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string DateTo = 6;</code>
       */
      public Builder setDateTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        dateTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateTo = 6;</code>
       */
      public Builder clearDateTo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        dateTo_ = getDefaultInstance().getDateTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string DateTo = 6;</code>
       */
      public Builder setDateToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        dateTo_ = value;
        onChanged();
        return this;
      }

      private java.util.List<es.encalient.ProtoMatchDTO.MatchDTO> matches_ =
        java.util.Collections.emptyList();
      private void ensureMatchesIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          matches_ = new java.util.ArrayList<es.encalient.ProtoMatchDTO.MatchDTO>(matches_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoMatchDTO.MatchDTO, es.encalient.ProtoMatchDTO.MatchDTO.Builder, es.encalient.ProtoMatchDTO.MatchDTOOrBuilder> matchesBuilder_;

      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public java.util.List<es.encalient.ProtoMatchDTO.MatchDTO> getMatchesList() {
        if (matchesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matches_);
        } else {
          return matchesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public int getMatchesCount() {
        if (matchesBuilder_ == null) {
          return matches_.size();
        } else {
          return matchesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public es.encalient.ProtoMatchDTO.MatchDTO getMatches(int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);
        } else {
          return matchesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder setMatches(
          int index, es.encalient.ProtoMatchDTO.MatchDTO value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.set(index, value);
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder setMatches(
          int index, es.encalient.ProtoMatchDTO.MatchDTO.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.set(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder addMatches(es.encalient.ProtoMatchDTO.MatchDTO value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder addMatches(
          int index, es.encalient.ProtoMatchDTO.MatchDTO value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(index, value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder addMatches(
          es.encalient.ProtoMatchDTO.MatchDTO.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder addMatches(
          int index, es.encalient.ProtoMatchDTO.MatchDTO.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder addAllMatches(
          java.lang.Iterable<? extends es.encalient.ProtoMatchDTO.MatchDTO> values) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, matches_);
          onChanged();
        } else {
          matchesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder clearMatches() {
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public Builder removeMatches(int index) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.remove(index);
          onChanged();
        } else {
          matchesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public es.encalient.ProtoMatchDTO.MatchDTO.Builder getMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public es.encalient.ProtoMatchDTO.MatchDTOOrBuilder getMatchesOrBuilder(
          int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);  } else {
          return matchesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public java.util.List<? extends es.encalient.ProtoMatchDTO.MatchDTOOrBuilder> 
           getMatchesOrBuilderList() {
        if (matchesBuilder_ != null) {
          return matchesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matches_);
        }
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public es.encalient.ProtoMatchDTO.MatchDTO.Builder addMatchesBuilder() {
        return getMatchesFieldBuilder().addBuilder(
            es.encalient.ProtoMatchDTO.MatchDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public es.encalient.ProtoMatchDTO.MatchDTO.Builder addMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().addBuilder(
            index, es.encalient.ProtoMatchDTO.MatchDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .es.encalient.MatchDTO matches = 7;</code>
       */
      public java.util.List<es.encalient.ProtoMatchDTO.MatchDTO.Builder> 
           getMatchesBuilderList() {
        return getMatchesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          es.encalient.ProtoMatchDTO.MatchDTO, es.encalient.ProtoMatchDTO.MatchDTO.Builder, es.encalient.ProtoMatchDTO.MatchDTOOrBuilder> 
          getMatchesFieldBuilder() {
        if (matchesBuilder_ == null) {
          matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              es.encalient.ProtoMatchDTO.MatchDTO, es.encalient.ProtoMatchDTO.MatchDTO.Builder, es.encalient.ProtoMatchDTO.MatchDTOOrBuilder>(
                  matches_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          matches_ = null;
        }
        return matchesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:es.encalient.WeekDTO)
    }

    static {
      defaultInstance = new WeekDTO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:es.encalient.WeekDTO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_encalient_WeekDTO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_es_encalient_WeekDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rWeekDTO.proto\022\014es.encalient\032\016MatchDTO." +
      "proto\"\224\001\n\007WeekDTO\022\n\n\002Id\030\001 \001(\003\022\016\n\006Season\030" +
      "\002 \001(\003\022\r\n\005Title\030\003 \001(\t\022\023\n\013Description\030\004 \001(" +
      "\t\022\020\n\010DateFrom\030\005 \001(\t\022\016\n\006DateTo\030\006 \001(\t\022\'\n\007m" +
      "atches\030\007 \003(\0132\026.es.encalient.MatchDTOB\016B\014" +
      "ProtoWeekDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          es.encalient.ProtoMatchDTO.getDescriptor(),
        }, assigner);
    internal_static_es_encalient_WeekDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_encalient_WeekDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_es_encalient_WeekDTO_descriptor,
        new java.lang.String[] { "Id", "Season", "Title", "Description", "DateFrom", "DateTo", "Matches", });
    es.encalient.ProtoMatchDTO.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
